language: python
sudo: false
matrix:
    include:
        -   env: TOXENV=py27 GO=1.6
        -   env: TOXENV=py27 GO=1.7
        -   env: TOXENV=py35 GO=1.7
            python: 3.5
        -   env: TOXENV=py36 GO=1.7
            python: 3.6
        -   env: TOXENV=pypy GO=1.7
            python: pypy
install:
    - eval "$(gimme $GO)"
    - pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
