language: python
env:
    - TOXENV=py27 GO=1.5
    - TOXENV=py27 GO=1.6
    - TOXENV=py34 GO=1.6
    - TOXENV=py35 GO=1.6
    - TOXENV=pypy GO=1.6
install:
    - eval "$(gimme $GO)"
    - pip install coveralls tox
script:
    - tox
after_success:
    - coveralls
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.4-dev
            - python3.5-dev
