trigger:
  branches:
    include: [master, test-me-*]

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.5

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27]
    os: linux
    name_postfix: _go_1_11
    pre_test:
    - task: GoTool@0
      inputs:
        version: '1.11.5'
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, py27, py36, py37]
    os: linux
    name_postfix: _go_1_12
    pre_test:
    - task: GoTool@0
      inputs:
        version: '1.12'
